### ISSUE TITLE
need fix for ctrl+c handling and process kill

### ISSUE THREAD

**Issue by elinesterov** [ilyanesterov/discover#2]
in current implementation when user hit ctrl+c while discover.sh is running following issues happen:
1) f_terminate used to save data/cleanup after user hit ctrl+c, but it doesn't exit process despite how many times you hit ctrl+c
2) trap f_terminate INT will only catch ctrl+c but if process get killed, no data will be saved
3) in f_terminate we create directory cancelled-`date +%H:%M:%S` and then move nmap and metasploit scans mv $name/ $base_dir/data/cancelled-`date +%H:%M:%S` 2>/dev/null. Potentially after we might get into trap creating directory with one name and moving data to another one because of change in seconds. 
4)same for Recon files

**Comment by L1ghtn1ng** [comment]
Thanks merging
